name: clean

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  #schedule:   
  #  - cron: '36 */2 * * *'   #国际标准时间，北京时间+8，即下午1点钟
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Conversion:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
      - name: Download convesion programs
        run: |
          #wget -q https://github.com/xmdhs/clash2singbox/releases/download/v0.1.4/clash2singbox-linux-amd64 -O clash2singbox
          #chmod +x ./clash2singbox
          # 下载转换工具
          #cp -r ./sing-box-subscribe-no-flask-2.7.0 ./sing-box-sub         
          #wget --backups=1 https://github.com/Toperlock/sing-box-subscribe/releases/download/v2.7.1/sing-box-subscribe-no-flask-2.7.1.zip
          #7z x -y sing-box-subscribe-no-flask-2.7.1.zip -o./download
          cp -r ./download/sing-box-subscribe-no-flask-2.7.1/* ./sing-box-sub
          rm -df ./sing-box-sub/sing-box-subscribe-no-flask-2.7.1
          #rm -fd ./download
          echo fine
        continue-on-error: true  # 即使出错也继续执行后续步骤
      #Commit
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply changes
