name: sb config conversion

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:   
    - cron: '36 */2 * * *'   #国际标准时间，北京时间+8，即下午1点钟
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Conversion:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      - name: install packages
        run: |
          pip install -r ./requirements.txt
      - name: startSubconverter
        run: |
          # run the container detached, forward internal port 25500 to host port 25500
          docker run -d --restart=always -p 2550:25500 tindy2013/subconverter:latest
          # then check its status
          #curl http://localhost:2550/version
          # if you see `subconverter vx.x.x backend` then the container is up and running
          docker ps
          sleep 5
      #下载clash配置
      - name: download and convert clash configs
        run: |
          curl -o ./sub/113.yaml "http://127.0.0.1:2550/sub?target=clash&url=https://raw.githubusercontent.com/aiboboxx/clashfree/main/clash.yml"
        continue-on-error: true  # 即使出错也继续执行后续步骤
      # 下载转换工具，再将上边3个clash配置转换为sb配置
      - name: Download convesion programs
        run: |
          #wget -q https://github.com/xmdhs/clash2singbox/releases/download/v0.1.4/clash2singbox-linux-amd64 -O clash2singbox
          #chmod +x ./clash2singbox
          # 下载转换工具
          #wget --backups=1 https://github.com/Toperlock/sing-box-subscribe/releases/download/v2.8.0/sing-box-subscribe-no-flask-2.8.0.zip
          #7z x -y sing-box-subscribe-no-flask-2.8.0.zip -o./download
          cp -rf ./download/sing-box-subscribe-no-flask-2.8.0 ./sing-box-sub
          rm ./sing-box-sub/README.md
          rm -fd ./download
          echo fine
        continue-on-error: true  # 即使出错也继续执行后续步骤

      - name: config conversion
        run: |          
          # 使用ls命令获取匹配的目录名
          matched_dirs=$(ls -d */ | grep sing-box-sub)
          # 检查匹配的目录数
          num_matched_dirs=$(echo "$matched_dirs" | wc -l)
          if [ $num_matched_dirs -eq 1 ]; then
            cd "${matched_dirs%/}"
          fi
          pwd
          python ./newmain.py -c prov-go.json
          mv go.json ../sub          
          cd ..
          pwd
        continue-on-error: true  # 即使出错也继续执行后续步骤
      - name:  clash2sb conversion for merged_proxies_new
        run: |
          ./clash2singbox -url https://raw.githubusercontent.com/Misaka-blog/chromego_merge/main/sub/merged_proxies_new.yaml -o ./sub/s1.json
        continue-on-error: true  # 即使出错也继续执行后续步骤

      # 下载转换工具，jq
      - name: Download jq programs
        run: |
          sudo apt install jq
        continue-on-error: true  # 即使出错也继续执行后续步骤
      - name: convert from urls, 生成k系列json
        run: |
          cd /home/runner/work/Honeybee/Honeybee/sing-box-sub
          chmod +x ./sbfromurls.sh
          bash ./sbfromurls.sh
          mv k*.json ../sub
        continue-on-error: true  # 即使出错也继续执行后续步骤
      - name: convert from urfls in local file, 生成f系列json
        run: |
          cd /home/runner/work/Honeybee/Honeybee/sing-box-sub
          bash ./sbfromtxt.sh
          mv f*.json ../sub
        continue-on-error: true  # 即使出错也继续执行后续步骤
      - name: Pull changes
        run: |
          git config --global user.email "wanghz518@gmail.com"
          git config --global user.name "shenmyisi"
          git pull origin main
      #Commit
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply changes
