# This is a basic workflow to help you get started with Actions

name: Config Conversion

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:   
    - cron: '36 */2 * * *'   #国际标准时间，北京时间+8，即下午1点钟
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Conversion:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      - name: install packages
        run: |
          pip install -r ./requirements.txt
      - name: startSubconverter
        run: |
          # run the container detached, forward internal port 25500 to host port 25500
          docker run -d --restart=always -p 2550:25500 tindy2013/subconverter:latest
          # then check its status
          #curl http://localhost:2550/version
          # if you see `subconverter vx.x.x backend` then the container is up and running
          docker ps
          sleep 5
      #下载clash配置
      - name: download and convert clash configs
        run: |
          curl -o ./sub/111.yaml "http://127.0.0.1:2550/sub?target=clash&url=https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.yml"
          curl -o ./sub/112.yaml "http://127.0.0.1:2550/sub?target=clash&url=https://raw.githubusercontent.com/freenodes/freenodes/main/clash.yaml"
          curl -o ./sub/113.yaml "http://127.0.0.1:2550/sub?target=clash&url=https://raw.githubusercontent.com/aiboboxx/clashfree/main/clash.yml"
        continue-on-error: true  # 即使出错也继续执行后续步骤
      # 下载转换工具，再将上边3个clash配置转换为sb配置
      - name: Download convesion programs
        run: |
          wget -q https://github.com/xmdhs/clash2singbox/releases/download/v0.1.4/clash2singbox-linux-amd64 -O clash2singbox
          chmod +x ./clash2singbox
          # 下载转换工具
          wget https://github.com/Toperlock/sing-box-subscribe/releases/download/v2.7.0/sing-box-subscribe-no-flask-2.7.0.zip
          7z x -y sing-box-subscribe-no-flask-2.7.0.zip
          echo remove download zip file
          if [ ! -f "./sing-box-subscribe-no-flask-2.7.0.zip" ];then
            rm ./sing-box-subscribe-no-flask-2.7.0.zip
          fi
        continue-on-error: true  # 即使出错也继续执行后续步骤
      - name: config conversion
        run: |          
          # 使用ls命令获取匹配的目录名
          matched_dirs=$(ls -d */ | grep sing-box-subscribe)
          # 检查匹配的目录数
          num_matched_dirs=$(echo "$matched_dirs" | wc -l)
          if [ $num_matched_dirs -eq 1 ]; then
            cd "${matched_dirs%/}"
          fi
          pwd
          cp ../sb_config_template/9*.json .
          cp ../newmain.py .
          cp ../prov-c*.json .
          python ./newmain.py -c prov-c1.json
          cd ..
          pwd
        continue-on-error: true  # 即使出错也继续执行后续步骤
      - name:  clash2sb conversion
        run: |
          ./clash2singbox -url https://raw.githubusercontent.com/Flik6/getNode/main/clash.yaml -o ./sub/config1.json
          ./clash2singbox -i ./sub/112.yaml -o ./sub/config2.json
          ./clash2singbox -i ./sub/113.yaml -o ./sub/config3.json
        continue-on-error: true  # 即使出错也继续执行后续步骤

      #Commit
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply changes
