
name: Delete old files

on:
  schedule:
    - cron:  '20 */2 * * *'  
jobs:
  delete_files:
    runs-on: ubuntu-latest
    name: Delete old files
    steps:
      - uses: actions/checkout@master
      - uses: daniL16/action-clean-old-files@master
        with:
          GITHUB_TOKEN: ${{ secrets.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 }}
          dir: './sub'
          base_branch: 'main'
          days_old: '3'
