# This is a basic workflow to help you get started with Actions

name: DownloadClean and Convertion

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:   
    - cron: '10 */1 * * *'   #国际标准时间，北京时间+8，即下午1点钟
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  download:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
      # Runs a single command using the runners shell
      - name: the download step
        run: |
          bash ./eop-clean.sh   

      # Runs a single command using the runners shell
      - name: Download Release
        run: |
          wget https://github.com/xmdhs/clash2singbox/releases/download/v0.1.4/clash2singbox-linux-amd64 -O clash2singbox
          chmod +x ./clash2singbox

      - name: Run clash2sb
        run: |
          ./clash2singbox -i ./htonly.yml -o ./config.json
          ./clash2singbox -i ./Config%20list1.txt -o ./config1.json
          ./clash2singbox -i ./Config%20list2.txt -o ./config2.json
          ./clash2singbox -i ./Config%20list3.txt -o ./config3.json
          ./clash2singbox -i ./Config%20list4.txt -o ./config4.json
          ./clash2singbox -i ./Config%20list5.txt -o ./config5.json
          ./clash2singbox -i ./Config%20list6.txt -o ./config6.json
          
      #Commit
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply changes
