name: Restore Deleted File

on:
  workflow_dispatch:  # 手动触发
  push:
    branches: [ main ]

jobs:
  restore-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 拉取完整历史记录
          persist-credentials: true  # 保留推送权限

      - name: Restore providers.json
        run: |
          # 从历史提交中恢复文件（注意替换为实际路径）
          git checkout f98e01afcd -- sb_config_template/9-config_template_no_groups.json
          git checkout f98e01afcd -- sing-box-sub/provx.json
          # 检查文件是否存在
          if [ ! -f "sing-box-sub/provx.json" ]; then
            echo "❌ 文件恢复失败，路径可能错误！"
            exit 1
          fi

      - name: Commit Restored File
        run: |
          # 配置Git用户信息
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # 暂存并提交恢复的文件
          git add sing-box-sub/provx.json
          git add sb_config_template/9-config_template_no_groups.json
          git commit -m "chore: 从提交 f98e01a 恢复 provx.json"

      - name: Pull Latest Changes
        run: |
          # 拉取远程最新代码并变基
          git pull origin main --rebase

      - name: Push Changes
        run: |
          # 推送更改
          git push origin main
