name: sb config verification

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  #schedule:   
  #  - cron: '45 */2 * * *'   #国际标准时间，北京时间+8，即下午1点钟
  #workflow_dispatch:
  #  inputs:
  #    workflow: { description: 'sb config verification' }
  workflow_run:
    workflows: ["sb config conversion"]  # 指定依赖的工作流名称
    types:
      - completed  # 只在工作流完成时触发

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  verification:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      - name: install packages
        run: |
          pip install -r ./requirements.txt
      - name: Clear cache
        run: git clean -fdx
      - name: Set working directory
        run: cd ./sing-box-sub
      # 下载转换工具，再将上边3个clash配置转换为sb配置
      - name: Download sing-box programs
        run: |
          wget -q https://github.com/SagerNet/sing-box/releases/download/v1.11.1/sing-box-1.11.1-linux-amd64.tar.gz
          7z x sing-box-1.11.1-linux-amd64.tar.gz 
          tar -xzf sing-box-1.11.1-linux-amd64.tar sing-box
          chmod +x ./sing-box
          ls -l ./sing-box
          echo fine
        continue-on-error: true  # 即使出错也继续执行后续步骤
      # 下载转换工具，jq
      - name: Download jq programs
        run: |
          sudo apt install jq
        continue-on-error: true  # 即使出错也继续执行后续步骤
      - name: Fix line endings
        run: |
          cd /home/runner/work/Honeybee/Honeybee/sing-box-sub
          sed -i 's/\r$//' ./check_clean.sh
          cat -A ./check_clean.sh # 查看换行符是否正常
        continue-on-error: true  # 即使出错也继续执行后续步骤
      - name: check and clean singbox config files
        run: |
          cd /home/runner/work/Honeybee/Honeybee/sub
          bash ../sing-box-sub/check_clean.sh
        continue-on-error: true  # 即使出错也继续执行后续步骤
      - name: Pull changes
        run: |
          git config --global user.email "wanghz518@gmail.com"
          git config --global user.name "shenmyisi"
          git pull origin main
      #Commit
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply changes
